sudo: false

language: cpp

compiler:
  - clang
  - gcc

install:
  # install cmake
  - CMAKE_VERSION="3.3.2"
  - wget "http://www.cmake.org/files/v3.3/cmake-${CMAKE_VERSION}.tar.gz"
  - openssl sha1 "cmake-${CMAKE_VERSION}.tar.gz"
  - tar xf "cmake-${CMAKE_VERSION}.tar.gz"
  - cd "cmake-${CMAKE_VERSION}"
  - ./bootstrap --prefix=~
  - make
  - make install
  - export PATH="~/bin:${PATH}"
  - cd ..
 
before_script:
  - BUILD_DIR=`pwd`/build/cmake
  - if [ ! -d ${BUILD_DIR} ] ; then mkdir -p ${BUILD_DIR} ; fi
  - cd ${BUILD_DIR}
  - cmake ../..

script:
  - cd ${BUILD_DIR}
  - make

