sudo: false

language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - cmake

# before_install:
#   - yes | sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
#   - sudo apt-get update -qq
# 
# install:
#   - sudo apt-get -y install cmake
 
before_script:
  - BUILD_DIR=`pwd`/build/cmake
  - if [ ! -d ${BUILD_DIR} ] ; then mkdir -p ${BUILD_DIR} ; fi
  - cd ${BUILD_DIR}
  - cmake ../..

script:
  - cd ${BUILD_DIR}
  - make

