language: c

compiler:
  - clang
  - gcc

before_install:
  - export SCRIPTS=./scripts/travis

install:
  - sudo -E $SCRIPTS/travis_install.sh

before_script:
  - BUILD_DIR=`pwd`/build/cmake
  - if [ ! -d ${BUILD_DIR} ] ; then mkdir -p ${BUILD_DIR} ; fi
  - cd ${BUILD_DIR}
  - cmake ../..

script:
  - cd ${BUILD_DIR}
  - make

