sudo: false

language: cpp

compiler:
  - clang
  - gcc

install:
  # install cmake
  - CMAKE_VERSION="3.3.2"
  - wget --no-check-certificate http://www.cmake.org/files/v3.3/cmake-${CMAKE_VERSION}-Linux-x86_64.sh
  - chmod a+x cmake-${CMAKE_VERSION}-Linux-x86_64.sh
  - ./cmake-${CMAKE_VERSION}-Linux-x86_64.sh --skip-license --prefix=${HOME}/.local/usr
  - export PATH=${HOME}/.local/usr/bin:$PATH
  - cmake --version
 
before_script:
  - BUILD_DIR=`pwd`/build/cmake
  - if [ ! -d ${BUILD_DIR} ] ; then mkdir -p ${BUILD_DIR} ; fi
  - cd ${BUILD_DIR}
  - cmake ../..

script:
  - cd ${BUILD_DIR}
  - make

